# Stage 1: Build the frontend
FROM node:18-alpine as builder

WORKDIR /app

# Install required image optimization tools
RUN apk add --no-cache gifsicle mozjpeg

# Install dependencies
COPY package*.json ./
RUN npm install --legacy-peer-deps

# Build the frontend
COPY . .
RUN npm run build

# Stage 2: Serve the built files with Nginx
FROM nginx:alpine

COPY --from=builder /app/build /usr/share/nginx/html
