# Use Node.js image
FROM node:16

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy source files
COPY . .

# Expose frontend port
EXPOSE 3005

# Start the app
CMD ["npm", "start"]
