# Use a Node.js image to build the frontend
FROM node:18-alpine AS builder

# Install dependencies for image optimization
RUN apk add --no-cache gifsicle libjpeg-turbo && npm install -g image-webpack-loader

WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install npm dependencies
RUN npm install --legacy-peer-deps

# Copy the rest of the source code
COPY . .

# Build the frontend
RUN npm run build

# Stage 2: Serve the built files with Nginx
FROM nginx:alpine

# Copy the build from the builder stage
COPY --from=builder /app/dist /usr/share/nginx/html




