const categoriesList = [
    { name: "Abstract Art", id: "ABSTRACT ART" },
    { name: "Realism", id: "REALISM" },
    { name: "Impressionism", id: "IMPRESSIONISM" },
    { name: "Expressionism", id: "EXPRESSIONISM" },
    { name: "Surrealism", id: "SURREALISM" },
    { name: "Minimalism", id: "MINIMALISM" },
    { name: "Cubism", id: "CUBISM" },
    { name: "Pop Art", id: "POP ART" },
    { name: "Street Art / Graffiti", id: "STREET ART / GRAFFITI" },
    { name: "Calligraphy & Typography Art", id: "CALLIGRAPHY & TYPOGRAPHY ART" },
    { name: "Portrait Art", id: "PORTRAIT ART" },
    { name: "Landscape Art", id: "LANDSCAPE ART" },
    { name: "Still Life", id: "STILL LIFE" },
    { name: "Photography", id: "PHOTOGRAPHY" },
    { name: "Sculpture", id: "SCULPTURE" },
    { name: "Fantasy & Mythology", id: "FANTASY & MYTHOLOGY" },
    { name: "Renaissance Art", id: "RENAISSANCE ART" },
    { name: "Baroque Art", id: "BAROQUE ART" },
    { name: "Gothic Art", id: "GOTHIC ART" },
    { name: "Modern Art", id: "MODERN ART" },
    { name: "Contemporary Art", id: "CONTEMPORARY ART" },
    { name: "Best-Selling Artists", id: "BEST-SELLING ARTISTS" },
    { name: "Famous Artists", id: "FAMOUS ARTISTS" },
    { name: "Seasonal Promotion", id: "SEASONAL PROMOTION" },
    { name: "Emerging Artists", id: "EMERGING ARTISTS" },
    { name: "Digital Art", id: "DIGITAL ART" },
    { name: "AI-Generated Art", id: "AI-GENERATED ART" },
    { name: "NFT Art", id: "NFT ART" },
    { name: "Cultural & Heritage Art", id: "CULTURAL & HERITAGE ART" },
    { name: "Mixed Media", id: "MIXED MEDIA" },
    { name: "New In", id: "NEW IN" },
    { name: "Print", id: "PRINT" },
    { name: "Drawing", id: "DRAWING" },
    { name: "More", id: "MORE" },
    { name: "Artists", id: "ARTISTS" },
    { name: "Featured Artist", id: "FEATURED ARTIST" },
    { name: "Painting", id: "PAINTING" },

  ];

  const mediumsList = [
    { name: "Acrylic", id: "ACRYLIC" },
    { name: "Bricks", id: "BRICKS" },
    { name: "Cement", id: "CEMENT" },
    { name: "Ceramics", id: "CERAMICS" },
    { name: "Chalk", id: "CHALK" },
    { name: "Charcoal", id: "CHARCOAL" },
    { name: "Collage", id: "COLLAGE" },
    { name: "Colored Pencil", id: "COLORED PENCIL" },
    { name: "Cotton", id: "COTTON" },
    { name: "Earth", id: "EARTH" },
    { name: "Embroidery", id: "EMBROIDERY" },
    { name: "Enamel", id: "ENAMEL" },
    { name: "Engraving", id: "ENGRAVING" },
    { name: "Epoxy", id: "EPOXY" },
    { name: "Felt", id: "FELT" },
    { name: "Gilding", id: "GILDING" },
    { name: "Gold leaf", id: "GOLD LEAF" },
    { name: "Gouache", id: "GOUACHE" },
    { name: "Graffiti", id: "GRAFFITI" },
    { name: "Graphite", id: "GRAPHITE" },
    { name: "India Ink", id: "INDIA INK" },
    { name: "Ink", id: "INK" },
    { name: "Lacquer", id: "LACQUER" },
    { name: "Latex", id: "LATEX" },
    { name: "Leather", id: "LEATHER" },
    { name: "Lithography", id: "LITHOGRAPHY" },
    { name: "Marble powder", id: "MARBLE POWDER" },
    { name: "Objects", id: "OBJECTS" },
    { name: "Oil", id: "OIL" },
    { name: "Oil Pastel", id: "OIL PASTEL" },
    { name: "Organic material", id: "ORGANIC MATERIAL" },
    { name: "Pastel", id: "PASTEL" },
    { name: "Pearl", id: "PEARL" },
    { name: "Pen", id: "PEN" },
    { name: "Pencil", id: "PENCIL" },
    { name: "Pigments", id: "PIGMENTS" },
    { name: "Plaster", id: "PLASTER" },
    { name: "Pyrofusion", id: "PYROFUSION" },
    { name: "Reclaimed objects", id: "RECLAIMED OBJECTS" },
    { name: "Relief Printing", id: "RELIEF PRINTING" },
    { name: "Resin", id: "RESIN" },
    { name: "Sand", id: "SAND" },
    { name: "Screen", id: "SCREEN" },
    { name: "Screen Printing", id: "SCREEN PRINTING" },
    { name: "Silver leaf", id: "SILVER LEAF" },
    { name: "Spray Paint", id: "SPRAY PAINT" },
    { name: "Staining", id: "STAINING" },
    { name: "Tape", id: "TAPE" },
    { name: "Tar", id: "TAR" },
    { name: "Tempera", id: "TEMPERA" },
    { name: "Vinyl", id: "VINYL" },
    { name: "Wax", id: "WAX" },
    { name: "Watercolor", id: "WATERCOLOR" },
    { name: "Wool", id: "WOOL" },
    { name: "Zinc", id: "ZINC" }
  ];

  const stylesList = [
    { name: "Aboriginal", id: "ABORIGINAL" },
    { name: "Abstract", id: "ABSTRACT" },
    { name: "Comics", id: "COMICS" },
    { name: "Cubism", id: "CUBISM" },
    { name: "Expressionism", id: "EXPRESSIONISM" },
    { name: "Fauvism", id: "FAUVISM" },
    { name: "Figurative", id: "FIGURATIVE" },
    { name: "Fine Art", id: "FINE ART" },
    { name: "Futuristic", id: "FUTURISTIC" },
    { name: "Geometric", id: "GEOMETRIC" },
    { name: "Impressionism", id: "IMPRESSIONISM" },
    { name: "Metaphysical", id: "METAPHYSICAL" },
    { name: "Minimalism", id: "MINIMALISM" },
    { name: "Naïve", id: "NAÏVE" },
    { name: "Oriental", id: "ORIENTAL" },
    { name: "Other", id: "OTHER" },
    { name: "Outsider", id: "OUTSIDER" },
    { name: "Pop Art", id: "POP ART" },
    { name: "Primitivism", id: "PRIMITIVISM" },
    { name: "Realism", id: "REALISM" },
    { name: "Semi-abstract", id: "SEMI-ABSTRACT" },
    { name: "Surrealism", id: "SURREALISM" },
    { name: "Symbolic", id: "SYMBOLIC" },
    { name: "Vintage", id: "VINTAGE" },
    { name: "Digital", id: "DIGITAL" },
    { name: "Black And White", id: "BLACK AND WHITE" },
    { name: "Impressionisn", id: "IMPRESSIONISN" },
    { name: "Color", id: "COLOR" },
    { name: "Street Photo", id: "STREET PHOTO" },
    { name: "Sepia", id: "SEPIA" },
  ];

  const themesList = [
    { name: "Nature & Wildlife", id: "NATURE & WILDLIFE" },
    { name: "Fantasy & Mythology", id: "FANTASY & MYTHOLOGY" },
    { name: "Love & Romance", id: "LOVE & ROMANCE" },
    { name: "Space & Universe", id: "SPACE & UNIVERSE" },
    { name: "Urban & City Life", id: "URBAN & CITY LIFE" },
    { name: "Historical Events", id: "HISTORICAL EVENTS" },
    { name: "Cultural & Heritage", id: "CULTURAL & HERITAGE" },
    { name: "Mystical & Esoteric", id: "MYSTICAL & ESOTERIC" },
    { name: "Dreams & Imagination", id: "DREAMS & IMAGINATION" },
    { name: "Abstract Concepts", id: "ABSTRACT CONCEPTS" },
    { name: "Dark & Gothic", id: "DARK & GOTHIC" },
    { name: "Light & Joyful", id: "LIGHT & JOYFUL" },
    { name: "War & Conflict", id: "WAR & CONFLICT" },
    { name: "Spiritual & Religious", id: "SPIRITUAL & RELIGIOUS" },
    { name: "Science & Futurism", id: "SCIENCE & FUTURISM" },
    { name: "Music & Dance", id: "MUSIC & DANCE" },
    { name: "Sports & Action", id: "SPORTS & ACTION" },
    { name: "Seasons & Weather", id: "SEASONS & WEATHER" },
    { name: "Portraits & People", id: "PORTRAITS & PEOPLE" },
    { name: "Animals & Pets", id: "ANIMALS & PETS" },
    { name: "Meditative & Zen", id: "MEDITATIVE & ZEN" },
    { name: "Chaos & Disorder", id: "CHAOS & DISORDER" },
    { name: "Minimalist & Simple", id: "MINIMALIST & SIMPLE" },
    { name: "Vibrant & Colorful", id: "VIBRANT & COLORFUL" },
    { name: "Black & White", id: "BLACK & WHITE" },
    { name: "Melancholic & Emotional", id: "MELANCHOLIC & EMOTIONAL" },
    { name: "Fantasy Landscapes", id: "FANTASY LANDSCAPES" },
    { name: "Underwater & Marine Life", id: "UNDERWATER & MARINE LIFE" },
    { name: "Surreal & Bizarre", id: "SURREAL & BIZARRE" },
    { name: "Symbolic & Hidden Meanings", id: "SYMBOLIC & HIDDEN MEANINGS" },
    { name: "Rebellion & Protest", id: "REBELLION & PROTEST" },
    { name: "Cyberpunk & Tech", id: "CYBERPUNK & TECH" },
    { name: "Pop Culture", id: "POP CULTURE" },
    { name: "Landscape", id: "LANDSCAPE" },
    { name: "Portrait", id: "PORTRAIT" },
    { name: "Urban", id: "URBAN" },
    { name: "Floral", id: "FLORAL" },
    { name: "Travel", id: "TRAVEL" },
    { name: "Nature", id: "NATURE" },
  ];

  module.exports = { categoriesList, mediumsList, stylesList, themesList };
